create table if not exists public.calculator_questions (
  id bigint generated by default as identity primary key,
  label text not null check (char_length(trim(label)) > 0),
  field_name text not null,
  type text not null check (type in ('select', 'text', 'checkbox')),
  options jsonb not null default '[]'::jsonb check (jsonb_typeof(options) = 'array'),
  "order" integer not null default 100,
  is_required boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint calculator_questions_field_name_format_chk check (
    lower(field_name) = field_name
    and field_name ~ '^[a-z][a-z0-9_]{1,62}$'
    and field_name <> all (
      array[
        'theme',
        'question',
        'birth_date',
        'birth_time',
        'birth_timezone',
        'birth_location',
        'birth_lat',
        'birth_lng',
        'place_query',
        'target_birth_date',
        'target_birth_time',
        'target_birth_timezone',
        'conflict_date',
        'transit_planet',
        'natal_planet',
        'aspect',
        'aspect_angle',
        'dynamic_answers',
        'year',
        'month'
      ]
    )
  )
);

create unique index if not exists calculator_questions_field_name_unique_idx
  on public.calculator_questions (field_name);

create index if not exists calculator_questions_order_idx
  on public.calculator_questions ("order" asc, id asc);

create index if not exists calculator_questions_active_idx
  on public.calculator_questions (is_active)
  where deleted_at is null;

alter table public.calculator_questions enable row level security;

drop policy if exists "Public can read active calculator questions" on public.calculator_questions;
create policy "Public can read active calculator questions"
  on public.calculator_questions
  for select
  to anon, authenticated
  using (is_active = true and deleted_at is null);

drop policy if exists "Admins can manage calculator questions" on public.calculator_questions;
create policy "Admins can manage calculator questions"
  on public.calculator_questions
  for all
  to authenticated
  using (
    exists (
      select 1
      from public.user_profiles up
      where up.id = auth.uid()
        and up.role = 'admin'
        and up.active = true
    )
  )
  with check (
    exists (
      select 1
      from public.user_profiles up
      where up.id = auth.uid()
        and up.role = 'admin'
        and up.active = true
    )
  );

drop policy if exists "Service role can manage calculator questions" on public.calculator_questions;
create policy "Service role can manage calculator questions"
  on public.calculator_questions
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');
